version: 2.1

jobs:
  deploy:
    docker:
      - image: circleci/node:10.19.0
    steps:
      - checkout
      - run: sudo npm install pug-cli -g
      - run: sudo npm install -g firebase-tools
      - run: pug pages
      - run: mkdir public
      - run: find pages -name \*.html -exec cp {} public \;
      - run: cp robots.txt public && cp sitemap.xml public && cp resume.pdf public
      - run: cp -R css public
      - run: cp -R js public
      - run: cp -R images public
      - run: firebase deploy --token=$FIREBASE_TOKEN --non-interactive

workflows:
  version: 2
  deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: master