version: 2.1

jobs:
  deploy:
    docker:
      - image: circleci/node:9.8.0
    steps:
      - checkout
      - run: sudo npm install pug-cli -g
      - run: sudo npm install -g firebase-tools
      - run: pug .
      - run: mkdir public && cp index.html public && cp gugweb.html public && cp raytools.html public && cp robots.txt public && cp sitemap.xml public && cp -R css public && cp -R js public && cp -R images public && cp resume.pdf public
      - run: firebase deploy --token=$FIREBASE_TOKEN --non-interactive

workflows:
  version: 2
  deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: master