version: 2.1

jobs:
  deploy:
    docker:
      - image: circleci/node:9.8.0
    steps:
      - checkout
      - run: npm install pug-cli -g
      - run: npm install -g firebase-tools
      - run: firebase deploy --token=$FIREBASE_TOKEN --non-interactive

workflows:
  version: 2
  deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: master